---
Name: keysforcache
---
SilverStripe\ORM\DataObject:
  extensions:
    CacheKeyExtension: Terraformers\KeysForCache\Extensions\CacheKeyExtension

Terraformers\KeysForCache\Models\CacheKey:
  blacklist:
    - Terraformers\KeysForCache\Models\CacheKey
    - SilverStripe\Versioned\ChangeSet
    - SilverStripe\Versioned\ChangeSetItem
    - SilverStripe\SessionManager\Models\LoginSession
    - SilverStripe\Snapshots\SnapshotItem
    - SilverStripe\Snapshots\Snapshot
